### ISSUE TITLE
How to run several services at once?

### ISSUE THREAD

**Issue by ItaloCobains** [cloudposse/github-action-docker-compose-test-run#19]
How to run several services at once?

I need run three services to test my app

```yml
name: Test CI

on:
  pull_request:
  push: { branches: main }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Tests
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: docker-compose.yml
          service: ""
          command: .ci/scripts/run-docker-test.sh
```
